# Generated by Django 4.2.1 on 2023-05-29 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT')], max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('manager', 'manager'), ('Software Developer', 'sd'), ('Project Leader', 'pl')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahir_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(choices=[('Phones', 'Phones'), ('Tablets', 'Tablets'), ('Laptops', 'Laptops'), ('Others', 'others')], default='phone', max_length=200)),
                ('Condition', models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Bad', 'Bad'), ('Damaged', 'Damaged')], default='New', max_length=100)),
                ('information', models.TextField()),
                ('Given_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Taken_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Employee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahir_api.company')),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahir_api.employee')),
            ],
        ),
    ]
